server:
  port: 8083
spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://212.129.248.48:3306/db_account?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
  cloud:
    alibaba:
      seata:
        tx-service-group: account-service-group
